/**
 * Mock data pro PREVIEW mode (cookie arbiq_preview=1).
 *
 * Návštěvník bez loginu si může portál „proklikat" a vidí vtipnou
 * fiktivní agenturu jejíž klienti jsou slavní detektivové. Žádná skutečná
 * data nejsou ohrožena, žádné mutating actions nejsou aktivní (queries
 * se simulují, server Actions selžou na RLS).
 */

export const PREVIEW_PROJECTS = [
  {
    id: 'demo-001',
    name: 'Případ ztracených konverzí',
    status: 've_vyvoji',
    progress: 67,
    estimated_end_date: '2026-05-30',
    nextMilestoneName: 'Design k revizi — Mrs. Hudson',
    nextMilestoneDate: '2026-04-30',
  },
  {
    id: 'demo-002',
    name: 'Vyšetřování pomalého e-shopu',
    status: 'k_revizi',
    progress: 92,
    estimated_end_date: '2026-04-28',
    nextMilestoneName: 'Final review s klientem',
    nextMilestoneDate: '2026-04-26',
  },
  {
    id: 'demo-003',
    name: 'Záhada zmizelého traffic-u',
    status: 'v_priprave',
    progress: 25,
    estimated_end_date: '2026-06-15',
    nextMilestoneName: 'Kick-off meeting',
    nextMilestoneDate: '2026-04-25',
  },
  {
    id: 'demo-004',
    name: 'Případ Jacka Rozparovače — forenzní web',
    status: 've_vyvoji',
    progress: 48,
    estimated_end_date: '2026-07-10',
    nextMilestoneName: 'Bezpečnostní audit (penetrace)',
    nextMilestoneDate: '2026-05-12',
  },
  {
    id: 'demo-005',
    name: 'Záhada Reichenbach Falls — SEO comeback',
    status: 've_vyvoji',
    progress: 34,
    estimated_end_date: '2026-08-20',
    nextMilestoneName: 'Klíčová slova — finální schválení',
    nextMilestoneDate: '2026-05-05',
  },
];

export const PREVIEW_INVOICES = [
  {
    id: 'demo-inv-001',
    invoice_number: 'F2026-00042',
    amount: 47000,
    description: 'Vyšetřování případu č. 221B — vývoj 1. fáze',
    issued_at: '2026-04-01',
    due_date: '2026-04-15',
    paid_at: '2026-04-12',
    status: 'zaplaceno',
    pdf_url: null,
  },
  {
    id: 'demo-inv-002',
    invoice_number: 'F2026-00043',
    amount: 38000,
    description: 'Bakerstreet redesign — sprint 2',
    issued_at: '2026-04-15',
    due_date: '2026-04-30',
    paid_at: null,
    status: 'ceka',
    pdf_url: null,
  },
  {
    id: 'demo-inv-003',
    invoice_number: 'F2026-00044',
    amount: 12500,
    description: 'Reichenbach falls — měsíční paušál SEO',
    issued_at: '2026-03-20',
    due_date: '2026-04-05',
    paid_at: null,
    status: 'po_splatnosti',
    pdf_url: null,
  },
  {
    id: 'demo-inv-004',
    invoice_number: 'F2026-00045',
    amount: 22000,
    description: 'Konzultace s Mycroftem H. — diplomatický tier',
    issued_at: '2026-04-18',
    due_date: '2026-05-02',
    paid_at: null,
    status: 'ceka',
    pdf_url: null,
  },
  {
    id: 'demo-inv-005',
    invoice_number: 'F2026-00046',
    amount: 4500,
    description: 'SSL certifikát + obnova domény 221b.uk (1 rok)',
    issued_at: '2026-04-20',
    due_date: '2026-05-04',
    paid_at: '2026-04-21',
    status: 'zaplaceno',
    pdf_url: null,
  },
];

export const PREVIEW_LEADS = [
  {
    id: 'demo-lead-001',
    created_at: '2026-04-23T08:30:00Z',
    case_number: 'LEAD-2026-00042',
    kampan: 'webove-stranky',
    obor: 'Detektivní služby',
    velikost_firmy: '1–10',
    step3_odpoved: 'Klesl mi traffic o 60 %',
    name: 'Inspektor Lestrade',
    email: 'lestrade@scotland-yard.uk',
    phone: '+44 20 7946 0958',
    website_url: 'https://scotland-yard.uk',
    popis: 'Hledám pomoc s redesignem firemního webu. Konkurence (Sherlock & spol.) nás předbíhá.',
    utm_source: 'meta',
    utm_medium: 'cpc',
    utm_campaign: 'detektivove-q2',
    status: 'new',
    assigned_to: null,
    notes: null,
  },
  {
    id: 'demo-lead-002',
    created_at: '2026-04-22T14:15:00Z',
    case_number: 'LEAD-2026-00041',
    kampan: 'rentgen',
    obor: 'Forenzní analýza',
    velikost_firmy: '11–50',
    step3_odpoved: 'Něco nefunguje, ale nevím co',
    name: 'Dr. John Watson',
    email: 'watson@221b.uk',
    phone: '+44 20 7224 3688',
    website_url: 'https://watson-medical.uk',
    popis: 'Kolega Holmes mě sem poslal. Chci Rentgen.',
    utm_source: 'referral',
    utm_medium: '',
    utm_campaign: '',
    status: 'contacted',
    assigned_to: '00000000-0000-0000-0000-000000001000',
    notes: null,
  },
  {
    id: 'demo-lead-003',
    created_at: '2026-04-21T11:45:00Z',
    case_number: 'LEAD-2026-00040',
    kampan: 'automatizace',
    obor: 'Krimi-spisovatelství',
    velikost_firmy: '1',
    step3_odpoved: 'Trávím 20+ hodin týdně rutinou',
    name: 'Hercule Poirot',
    email: 'poirot@belgian-detective.be',
    phone: '+32 2 555 0142',
    website_url: 'https://poirot.be',
    popis: 'Mes petites cellules grises potřebují víc času na případy. Automatizujte fakturaci.',
    utm_source: 'google',
    utm_medium: 'organic',
    utm_campaign: '',
    status: 'qualified',
    assigned_to: '00000000-0000-0000-0000-000000001000',
    notes: 'Velmi specifický klient. Vyžaduje pořádek a metodu.',
  },
  {
    id: 'demo-lead-004',
    created_at: '2026-04-20T09:00:00Z',
    case_number: 'LEAD-2026-00039',
    kampan: 'remeslnici',
    obor: 'Truhlář',
    velikost_firmy: '1',
    step3_odpoved: 'Žádné nové zakázky',
    name: 'Geppetto Carpentry',
    email: 'geppetto@toyworkshop.it',
    phone: null,
    website_url: 'https://geppetto.it',
    popis: 'Vyrábím loutky. Potřebuji web aby mě zákazníci našli.',
    utm_source: 'meta',
    utm_medium: 'cpc',
    utm_campaign: 'remeslnici-jaro',
    status: 'converted',
    assigned_to: '00000000-0000-0000-0000-000000001000',
    notes: 'Úžasný klient. Jeho loutky umí mluvit.',
  },
];

export const PREVIEW_TASKS = [
  {
    id: 'demo-task-001',
    title: 'Kontaktovat Mycrofta Holmese ohledně Pamatiq',
    description: 'Bratr klienta. Zájem o enterprise verzi.',
    priority: 'high',
    status: 'todo',
    due_date: '2026-04-25',
    client_id: null,
    lead_id: null,
    client: null,
    lead: { name: 'Sherlock Holmes', case_number: 'LEAD-2026-00038' },
  },
  {
    id: 'demo-task-002',
    title: 'Follow-up s Inspektorem Lestrade',
    description: '7 dní bez odpovědi po prvním kontaktu.',
    priority: 'normal',
    status: 'todo',
    due_date: '2026-04-26',
    client_id: null,
    lead_id: 'demo-lead-001',
    client: null,
    lead: { name: 'Inspektor Lestrade', case_number: 'LEAD-2026-00042' },
  },
  {
    id: 'demo-task-003',
    title: 'Připravit nabídku — Geppetto loutkářství',
    description: 'Web + e-shop + napojení na Etsy.',
    priority: 'high',
    status: 'in_progress',
    due_date: '2026-04-24',
    client_id: null,
    lead_id: 'demo-lead-004',
    client: { full_name: 'Geppetto Carpentry' },
    lead: null,
  },
  {
    id: 'demo-task-004',
    title: 'Faktura pro Watsona — splatnost dnes',
    description: '',
    priority: 'urgent',
    status: 'todo',
    due_date: '2026-04-24',
    client_id: null,
    lead_id: null,
    client: { full_name: 'Dr. John Watson' },
    lead: null,
  },
  {
    id: 'demo-task-005',
    title: 'Prozkoumat zda Moriarty není konkurence',
    description: 'Tip od jednoho z klientů. Zní podezřele.',
    priority: 'low',
    status: 'todo',
    due_date: null,
    client_id: null,
    lead_id: null,
    client: null,
    lead: null,
  },
  {
    id: 'demo-task-006',
    title: 'Renew SSL pro 221b.uk (před expirací)',
    description: 'Letsencrypt auto-renew selhalo, manuálně.',
    priority: 'high',
    status: 'todo',
    due_date: '2026-04-25',
    client_id: null,
    lead_id: null,
    client: { full_name: 'Dr. John Watson' },
    lead: null,
  },
  {
    id: 'demo-task-007',
    title: 'Follow-up Irene Adler — VIP klient',
    description: 'Avizovala že chce upgrade na enterprise. Volat zítra mezi 14-16h.',
    priority: 'high',
    status: 'todo',
    due_date: '2026-04-26',
    client_id: null,
    lead_id: null,
    client: { full_name: 'Irene Adler' },
    lead: null,
  },
  {
    id: 'demo-task-008',
    title: 'Vyšetřit padělanou recenzi (Yelp)',
    description: 'Někdo nám dal 1*. Lestrade tvrdí že to byl Moriartyho podržtaška.',
    priority: 'normal',
    status: 'in_progress',
    due_date: '2026-04-28',
    client_id: null,
    lead_id: null,
    client: null,
    lead: null,
  },
];

export const PREVIEW_RECOMMENDATIONS = [
  {
    id: 'demo-rec-001',
    service_name: 'Botiq pro Bakerstreetské stránky',
    description: 'AI poradce, který pomůže návštěvníkům najít přesně to, co hledají. Pro detektivní agenturu ideální — automatizuje first contact a kvalifikuje dotazy podle obvyklých vzorů.',
    estimated_price: 'od 4 900 Kč / měsíc',
    status: 'zobrazena',
  },
  {
    id: 'demo-rec-002',
    service_name: 'Pamatiq pro klienty s Alzheimerem',
    description: 'Vaši klienti zapomínají na schůzky. Pamatiq jim pošle připomínku přes Messenger den předem a 2 hodiny před. Zvyšuje show-up rate o 40 %.',
    estimated_price: 'od 1 900 Kč / měsíc',
    status: 'nova',
  },
  {
    id: 'demo-rec-003',
    service_name: 'Reklamiq — Lead z Meta Ads → SMS do 60 s',
    description: 'Holmes ztrácí 30 % nových klientů, protože odpovídá až za 4 hodiny. Reklamiq pošle SMS okamžitě jakmile přijde lead z reklamy. Konverze +25 %.',
    estimated_price: 'od 2 400 Kč / měsíc',
    status: 'nova',
  },
  {
    id: 'demo-rec-004',
    service_name: 'Linkediq — B2B outreach pro forenzní služby',
    description: 'Cílíme na compliance manažery a CISO. Personalizované zprávy které LinkedIn neoznačí jako bot. 4-6 kvalifikovaných leadů týdně.',
    estimated_price: 'od 5 900 Kč / měsíc',
    status: 'zobrazena',
  },
];

export const PREVIEW_USERS_FOR_ADMIN = [
  {
    id: '00000000-0000-0000-0000-000000001000',
    full_name: 'Sherlock Holmes (demo)',
    email: 'preview@arbiq.cz',
    role: 'admin' as const,
    is_active: true,
    assigned_obchodnik: null,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'demo-u-001',
    full_name: 'Dr. John Watson',
    email: 'watson@221b.uk',
    role: 'klient' as const,
    is_active: true,
    assigned_obchodnik: '00000000-0000-0000-0000-000000001000',
    created_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'demo-u-002',
    full_name: 'Inspektor Lestrade',
    email: 'lestrade@scotland-yard.uk',
    role: 'obchodnik' as const,
    is_active: true,
    assigned_obchodnik: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'demo-u-003',
    full_name: 'Hercule Poirot',
    email: 'poirot@belgian-detective.be',
    role: 'klient' as const,
    is_active: true,
    assigned_obchodnik: 'demo-u-002',
    created_at: '2026-03-20T00:00:00Z',
  },
  {
    id: 'demo-u-004',
    full_name: 'Professor Moriarty',
    email: 'moriarty@academy.uk',
    role: 'klient' as const,
    is_active: false,
    assigned_obchodnik: null,
    created_at: '2026-04-01T00:00:00Z',
  },
];

export const PREVIEW_KLIENTI_FOR_CRM = PREVIEW_USERS_FOR_ADMIN
  .filter((u) => u.role === 'klient')
  .map((u) => ({
    ...u,
    company: u.full_name.includes('Watson') ? 'Watson Medical Ltd.' : u.full_name.includes('Poirot') ? 'Poirot Investigations s.r.o.' : null,
    projects: u.id === 'demo-u-001' ? [{ id: 'demo-001', total_value: 85000, status: 've_vyvoji' }] : [],
  }));

export const PREVIEW_STATS = {
  revenueAllTime: 1_247_500,
  revenueThisMonth: 165_000,
  activeClients: 7,
  pipelineValue: 380_000,
  leadsLast90: 23,
  conversionRate: 26,
  topKampan: 'webove-stranky',
  topKampanCount: 9,
};
